spring:
  # ===============================
  # ===== Application config ======
  # ===============================

  application:
    name: subscription-service
  # ===============================
  # ===== Datasource config =======
  # ===============================
  sql:
    init:
      mode: always
      schema-locations: classpath:/sql/schema.sql
  datasource:
    url: jdbc:postgresql://localhost:5432/trivago_subscription_db?characterEncoding=UTF-8
    driver-class-name: org.postgresql.Driver
    username: app_user
    password: app_password
    platform: postgres
  # ===============================
  # ========= JPA config ==========
  # ===============================

  jpa:
    hibernate:
      ddl-auto: update #create-drop
    properties:
      hibernate:
        jdbc:
          batch_size: 5
    show-sql: true

# ===============================
# ======== Swagger config =======
# ===============================
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    operations-sorter: alpha
    tagsSorter: alpha
    enabled: 'true'
  packages-to-scan: com.trivago.subscription
