CREATE TABLE subscription (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hotel_id BIGINT,
    next_payment_on DATE,
    start_date DATE,
    end_date DATE,
    term SMALLINT,
    status SMALLINT,
    CHECK (status >= 0 AND status <= 2),
    CHECK (term >= 0 AND term <= 1)
);
